sudo: false
language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.8.7 DJANGO_SETTINGS_MODULE='settings_sqllite'
  - DJANGO=1.8.7 DJANGO_SETTINGS_MODULE='settings_postgres'
  - DJANGO=1.8.7 DJANGO_SETTINGS_MODULE='settings_mysql'
  - DJANGO=1.9 DJANGO_SETTINGS_MODULE='settings_sqllite'
  - DJANGO=1.9 DJANGO_SETTINGS_MODULE='settings_postgres'
  - DJANGO=1.9 DJANGO_SETTINGS_MODULE='settings_mysql'
  - DJANGO=1.10.1 DJANGO_SETTINGS_MODULE='settings_sqllite'
  - DJANGO=1.10.1 DJANGO_SETTINGS_MODULE='settings_postgres'
  - DJANGO=1.10.1 DJANGO_SETTINGS_MODULE='settings_mysql'
addons:
  - postgresql: "9.3"
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install coveralls
  - pip install -r test_requirements.pip
script:
  - coverage run --source=django_cron setup.py test
after_success:
  - coveralls
before_script:
  - mysql -e 'create database travis_test;'
  - psql -c 'create database travis_test;' -U postgres
  - flake8 . --config=flake8
