dist: bionic
os: linux
language: python
jobs:
  include:
    - python: "2.7"
      env: DJANGO=1.11.* DJANGO_SETTINGS_MODULE='settings_sqllite'
    - python: "2.7"
      env: DJANGO=1.11.* DJANGO_SETTINGS_MODULE='settings_postgres'
      services:
        - postgresql
      before_script:
        - psql -c 'create database travis_test;' -U postgres
    - python: "2.7"
      env: DJANGO=1.11.* DJANGO_SETTINGS_MODULE='settings_mysql'
      services:
        - mysql
      before_script:
        - mysql -e 'create database travis_test;'
    - python: "3.7"
      env: DJANGO=1.11.* DJANGO_SETTINGS_MODULE='settings_sqllite'
    - python: "3.7"
      env: DJANGO=2.0.* DJANGO_SETTINGS_MODULE='settings_sqllite'
    - python: "3.7"
      env: DJANGO=3.0.* DJANGO_SETTINGS_MODULE='settings_sqllite'
    - python: "3.7"
      env: DJANGO=3.0.* DJANGO_SETTINGS_MODULE='settings_postgres'
      services:
        - postgresql
      before_script:
        - psql -c 'create database travis_test;' -U postgres
    - python: "3.7"
      env: DJANGO=3.0.* DJANGO_SETTINGS_MODULE='settings_mysql'
      services:
        - mysql
      before_script:
        - mysql -e 'create database travis_test;'
install:
  - pip install -q Django==$DJANGO
  - pip install coveralls
  - pip install -r test_requirements.txt
script:
  - flake8 . --config=flake8
  - coverage run --source=django_cron setup.py test
after_success:
  - coveralls